name: hiru_super
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.9.0 

  # ✅ Firebase packages
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.5

  # ✅ Image Picker
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ✅ Add this section to include your local image assets
  assets:
    - assets/images/fish.jpg
    - assets/images/meat.jpg
    - assets/images/vegetables.jpg
    - assets/images/fruit.jpg
    - assets/images/beverages.jpg
    - assets/images/grocery.jpg

    - assets/images/balaya.jpg
    - assets/images/fish_banner.jpg
    - assets/images/cuttlefish.jpg    #fish_item images path
    - assets/images/prawns.jpg
    - assets/images/thalapath.jpg
    - assets/images/map_image.jpg
