// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH0UIhZIrC9gz7wXmlUnklgdzSMcKNJro',
    appId: '1:93275767384:web:3dde8ea01114dced1ac02d',
    messagingSenderId: '93275767384',
    projectId: 'hirusuper-206ab',
    authDomain: 'hirusuper-206ab.firebaseapp.com',
    storageBucket: 'hirusuper-206ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCspKBrfQ_bB3RWDcKe1AH6uCXfyJq-Seo',
    appId: '1:93275767384:android:ee01be725be75c421ac02d',
    messagingSenderId: '93275767384',
    projectId: 'hirusuper-206ab',
    storageBucket: 'hirusuper-206ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFmoNor4OvFRw9oNJncjLy9KSPBroBh-0',
    appId: '1:93275767384:ios:270c940381fe61791ac02d',
    messagingSenderId: '93275767384',
    projectId: 'hirusuper-206ab',
    storageBucket: 'hirusuper-206ab.firebasestorage.app',
    iosBundleId: 'com.example.hiruSuper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFmoNor4OvFRw9oNJncjLy9KSPBroBh-0',
    appId: '1:93275767384:ios:270c940381fe61791ac02d',
    messagingSenderId: '93275767384',
    projectId: 'hirusuper-206ab',
    storageBucket: 'hirusuper-206ab.firebasestorage.app',
    iosBundleId: 'com.example.hiruSuper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH0UIhZIrC9gz7wXmlUnklgdzSMcKNJro',
    appId: '1:93275767384:web:efab03279cd82c951ac02d',
    messagingSenderId: '93275767384',
    projectId: 'hirusuper-206ab',
    authDomain: 'hirusuper-206ab.firebaseapp.com',
    storageBucket: 'hirusuper-206ab.firebasestorage.app',
  );
}
